example
exampleWithNote
	^ 'From e-prints@arxiv.org Sun Feb 16 14:56:26 2020
Return-Path: e-prints@arxiv.org
To: nicolas.anquetil@inria.fr
From: e-prints@arxiv.org
Subject: arXiv submission
Date: Sun, 16 Feb 2020 08:56:18 -0500
Content-Type: multipart/mixed; boundary="=-U19OAwka/AclnO2vl3Z7"
MIME-Version: 1.0


--=-U19OAwka/AclnO2vl3Z7
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit


View the submission at http://arxiv.org/mod/123456789
From: Tan Author <tan.author@some.place>
Date: Sun, 16 Feb 2020 08:56:07 EST   (587kb,D)

Title: This is a Title
  on 2 lines
Authors: These are the authors
  on several lines
  also
Categories: cs.SE
Classifier: cs.SE 1
Status: next

  And this is a multi line abstract.
It is a bit uninformative, but we don''t care,
as it is for testing purposes

--=-U19OAwka/AclnO2vl3Z7
X-Evolution-Note: True
Content-Disposition: inline
Content-Description: Message Note
Content-Type: message/rfc822

From: me
Date: Mon, 17 Feb 2020 10:24:46 +0100
Subject: Message Note
Message-ID: <b40be4539c357bbc53320a318d065c5c171f322c.camel@przewalski>
Content-Type: text/plain
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit

keyword1
key word2

--=-U19OAwka/AclnO2vl3Z7--

'