example
exampleSimple
	^ 'From e-prints@arxiv.org Fri Mar 12 09:23:00 2021
Return-Path: <e-prints@arxiv.org>
To: nicolas.anquetil@inria.fr
From: e-prints@arxiv.org
Subject: arXiv submission submit/3646706 to cs.SE by Miroslaw Staron
Content-Type: text/plain; charset=utf-8
Message-Id: <submit.3646706@arxiv.org>
X-Evolution-Source: 7a3e51702fc394751839a3888502b1b6602b2755
Content-Transfer-Encoding: 8bit
MIME-Version: 1.0


View the submission at http://arxiv.org/mod/123456789
From: Tan Author <tan.author@some.place>
Date: Sun, 16 Feb 2020 08:56:07 EST   (587kb,D)

Title: This is a Title
  on 2 lines
Authors: These are the authors
  on several lines
  also
Categories: cs.SE
Classifier: cs.SE 0.95 cs.AB 0.21 cs.CD 0.15
Status: next

  And this is a multi line abstract.
It is a bit uninformative, but we don''t care,
as it is for testing purposes

'